"""
data_loader.py
--------------
Loads shl_product_catalog_expanded.json (generated by scrapper/expand_test_types.py)
and builds:
  1. FAISS dense vector index  — semantic similarity search
  2. BM25 sparse index         — keyword/token match

Design decisions explained in README_technical.md
"""

from __future__ import annotations
import json
import pickle
from pathlib import Path
from typing import List, Dict, Any, Tuple

from langchain_community.vectorstores import FAISS
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_core.documents import Document
from rank_bm25 import BM25Okapi


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
# APP_DIR = the directory containing this repo's root files (api.py, requirements.txt, etc.)
# Locally:  RdsSys/shl-rag-api/  (data_loader is at shl-rag-api/core/data_loader.py)
# Docker:   /app/                 (data_loader is at /app/core/data_loader.py)
# Both resolve correctly with parent.parent (2 levels up from this file)
APP_DIR = Path(__file__).resolve().parent.parent

# Prefer the expanded catalog; fall back to original if not present
EXPANDED_CATALOG = APP_DIR / "shl_product_catalog_expanded.json"
ORIGINAL_CATALOG = APP_DIR / "shl_product_catalog.json"
CATALOG_PATH     = EXPANDED_CATALOG if EXPANDED_CATALOG.exists() else ORIGINAL_CATALOG

# Indices live alongside the catalog in APP_DIR
FAISS_INDEX_PATH = APP_DIR / "faiss_index"
BM25_INDEX_PATH  = APP_DIR / "bm25_index.pkl"

# ---------------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------------
# Why BAAI/bge-base-en-v1.5 over all-MiniLM-L6-v2?
#   • BGE-base scores ~63.6 on BEIR vs MiniLM's ~59.1 (+4.5 points)
#   • Better at distinguishing domain-specific text (HR, assessments)
#   • Instruction prefix "Represent this sentence for searching relevant passages:"
#     improves asymmetric retrieval (short query → long doc)
#   • Dimension: 768 vs 384 — richer representation
#   • Still free and runs locally, no API cost
EMBEDDING_MODEL_NAME = "BAAI/bge-base-en-v1.5"
BGE_QUERY_PREFIX     = "Represent this sentence for searching relevant passages: "

TEST_TYPE_MAP = {
    "A": "Ability & Aptitude",
    "B": "Biodata & Situational Judgement",
    "C": "Competencies",
    "D": "Development & 360",
    "E": "Assessment Exercises",
    "K": "Knowledge & Skills",
    "P": "Personality & Behavior",
    "S": "Simulations",
}


# ---------------------------------------------------------------------------
# Load catalog
# ---------------------------------------------------------------------------
def _load_catalog() -> List[Dict[str, Any]]:
    print(f"[DataLoader] Using catalog: {CATALOG_PATH.name}")
    with open(CATALOG_PATH, "r", encoding="utf-8") as f:
        raw = json.load(f)
    products = [p for p in raw if p.get("Category") == "Individual Test Solutions"]
    print(f"[DataLoader] Loaded {len(products)} Individual Test Solutions")
    return products


# ---------------------------------------------------------------------------
# Document construction
# ---------------------------------------------------------------------------
def _get_test_type_display(product: Dict[str, Any]) -> str:
    """
    Get human-readable test type string.
    Uses 'Test Type' field (which is full names if expanded catalog is used,
    or letter codes if original catalog).
    """
    raw = product.get("Test Type", "")
    # If expanded catalog: already full names
    if product.get("Test Type Full"):
        return ", ".join(product["Test Type Full"])
    # Fallback: expand codes ourselves
    codes = [c.strip() for c in raw.split(",") if c.strip()]
    return ", ".join(TEST_TYPE_MAP.get(c, c) for c in codes)


def _get_test_type_codes(product: Dict[str, Any]) -> List[str]:
    """Return list of letter codes for structured filtering."""
    if product.get("Test Type Codes"):
        return product["Test Type Codes"]
    raw = product.get("Test Type", "")
    return [c.strip() for c in raw.split(",") if c.strip()]


def _build_documents(products: List[Dict[str, Any]]) -> List[Document]:
    """
    CHUNKING STRATEGY:
    ------------------
    Each SHL product becomes ONE Document (1:1 mapping, no splitting).
    Why no chunking here?
      • Each product is a short, self-contained record (avg ~150 tokens).
      • Splitting would destroy the contextual unit — a partial chunk about
        "Java" in a ".NET" assessment would cause false positives.
      • The embedding model handles up to 512 tokens; all records fit easily.

    CONTENT STRUCTURE:
    ------------------
    We use a "semantic field template" format rather than raw JSON dump.
    Each field has a label so the embedding captures field semantics, not
    just token co-occurrence. Fields are ordered from most to least
    discriminative for retrieval:
      1. Assessment name (most unique identifier)
      2. Test category (Ability, Knowledge, Personality…)
      3. Description (richest semantic signal)
      4. Semantic tags (manually derived synonyms for better recall)
      5. Job levels (for role-based queries)
      6. Logistics (remote, adaptive, duration)

    SEMANTIC TAGS:
    --------------
    We derive extra keywords from the test type so the embedding can match:
      "Knowledge & Skills" → tags: "technical skill test, proficiency test, domain knowledge"
      "Personality & Behavior" → tags: "behavioral assessment, soft skills, personality test"
    This directly fixes the "writing proficiency → C++ result" problem by
    ensuring personality/behavior assessments have strong soft-skill signals.
    """
    # Semantic tag expansions per test type — adds retrieval vocabulary
    TYPE_TAGS = {
        "A": "cognitive ability, aptitude test, reasoning, numerical, verbal, abstract thinking",
        "B": "biodata, situational judgement test, SJT, work scenarios, job fit",
        "C": "competency assessment, leadership, management skills, behavioral competency",
        "D": "development, 360 feedback, growth, coaching, self-assessment",
        "E": "exercises, simulation exercise, in-tray, role play, written exercise",
        "K": "technical skill, knowledge test, domain expertise, programming, language proficiency, software",
        "P": "personality test, behavioral assessment, soft skills, interpersonal, communication, teamwork, collaboration, work style",
        "S": "simulation, realistic job preview, virtual assessment, job simulation",
    }

    docs = []
    for p in products:
        type_display = _get_test_type_display(p)
        type_codes   = _get_test_type_codes(p)

        # Build semantic tags from all type codes
        semantic_tags = "; ".join(
            TYPE_TAGS[c] for c in type_codes if c in TYPE_TAGS
        )

        description = p.get("Description", "").strip()
        job_levels  = p.get("Job Levels", "").strip().rstrip(",")

        # ---- Page content (used for embedding) ----
        # Ordered: most discriminative fields first and last (anti lost-in-middle)
        content = (
            f"Assessment Name: {p.get('Product Name', '')}\n"
            f"Assessment Category: {type_display}\n"
            f"Description: {description}\n"
            f"Semantic Tags: {semantic_tags}\n"
            f"Job Levels: {job_levels}\n"
            f"Remote Testing Available: {p.get('Remote Testing', '')}\n"
            f"Adaptive/IRT: {p.get('Adaptive/IRT', '')}\n"
            f"Assessment Duration: {p.get('Assessment Length', '')}\n"
            # Repeat name + category at end (anti lost-in-middle for embeddings)
            f"Summary: {p.get('Product Name', '')} is a {type_display} assessment."
        )

        # ---- Parse duration ----
        duration = None
        length_str = p.get("Assessment Length", "")
        if "=" in length_str:
            try:
                duration = int(length_str.split("=")[-1].strip())
            except ValueError:
                pass

        # ---- Metadata (used for filtering & response construction) ----
        metadata = {
            "name":             p.get("Product Name", ""),
            "url":              p.get("Product URL", ""),
            "adaptive_support": p.get("Adaptive/IRT", "No"),
            "remote_support":   p.get("Remote Testing", "No"),
            "test_type_codes":  type_codes,
            "test_type_full":   [TEST_TYPE_MAP.get(c, c) for c in type_codes],
            "test_type_display": type_display,
            "description":      description,
            "duration":         duration,
            "job_levels":       job_levels,
            "languages":        p.get("Languages", ""),
        }
        docs.append(Document(page_content=content, metadata=metadata))

    return docs


# ---------------------------------------------------------------------------
# Embedding model
# ---------------------------------------------------------------------------
def _get_embedding_model() -> HuggingFaceEmbeddings:
    return HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={"device": "cpu"},
        encode_kwargs={"normalize_embeddings": True},  # cosine similarity requires L2 norm
    )


# ---------------------------------------------------------------------------
# Build or load indices
# ---------------------------------------------------------------------------
def build_or_load_indices() -> Tuple[FAISS, BM25Okapi, List[Document]]:
    """
    First run  → builds FAISS + BM25 from scratch, saves to disk.
    Later runs → loads from disk (fast).

    IMPORTANT: Delete faiss_index/ and bm25_index.pkl to force a rebuild
    after changing the catalog or embedding model.
    """
    products = _load_catalog()
    docs = _build_documents(products)
    embedding_model = _get_embedding_model()

    # ---- FAISS ----
    if FAISS_INDEX_PATH.exists():
        print("[DataLoader] Loading FAISS index from disk...")
        faiss_store = FAISS.load_local(
            str(FAISS_INDEX_PATH),
            embedding_model,
            allow_dangerous_deserialization=True,
        )
    else:
        print("[DataLoader] Building FAISS index — first run, may take ~2 minutes...")
        faiss_store = FAISS.from_documents(docs, embedding_model)
        faiss_store.save_local(str(FAISS_INDEX_PATH))
        print(f"[DataLoader] FAISS index saved → {FAISS_INDEX_PATH}")

    # ---- BM25 ----
    if BM25_INDEX_PATH.exists():
        print("[DataLoader] Loading BM25 index from disk...")
        with open(BM25_INDEX_PATH, "rb") as f:
            bm25_index = pickle.load(f)
    else:
        print("[DataLoader] Building BM25 index...")
        # Tokenise the full page_content for each document
        tokenized_corpus = [doc.page_content.lower().split() for doc in docs]
        bm25_index = BM25Okapi(tokenized_corpus)
        with open(BM25_INDEX_PATH, "wb") as f:
            pickle.dump(bm25_index, f)
        print(f"[DataLoader] BM25 index saved → {BM25_INDEX_PATH}")

    return faiss_store, bm25_index, docs
